# Form implementation generated from reading ui file 'AddNoteWind.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddNoteWindow(object):
    def setupUi(self, AddNoteWindow):
        AddNoteWindow.setObjectName("AddNoteWindow")
        AddNoteWindow.resize(800, 216)
        self.centralwidget = QtWidgets.QWidget(AddNoteWindow)
        self.centralwidget.setObjectName("centralwidget")
        AddNoteWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddNoteWindow)
        QtCore.QMetaObject.connectSlotsByName(AddNoteWindow)

    def retranslateUi(self, AddNoteWindow):
        _translate = QtCore.QCoreApplication.translate
        AddNoteWindow.setWindowTitle(_translate("AddNoteWindow", "AddNoteWind"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddNoteWindow = QtWidgets.QMainWindow()
    ui = Ui_AddNoteWindow()
    ui.setupUi(AddNoteWindow)
    AddNoteWindow.show()
    sys.exit(app.exec())
